// ============================================================
// Starter Repo Generator
// Generates complete starter codebase blueprints
// ============================================================

import { ProductBuild, BuildVariant, TechLayer, AgentRole } from "@/lib/agents/types";

export interface StarterBlueprint {
  name: string;
  description: string;
  variant: string;
  folderStructure: Record<string, any>;
  readme: string;
  dockerCompose: string;
  envExample: string;
  packageJson: Record<string, any>;
  mainConfig: string;
  agentFiles: Array<{ path: string; content: string }>;
  apiRoutes: Array<{ path: string; content: string }>;
}

/**
 * Generate a complete starter repo blueprint for a product
 */
export function generateStarterRepo(product: ProductBuild, variantTier: string = "intermediate"): StarterBlueprint {
  const variant = product.buildVariants.find(v => v.tier === variantTier) || product.buildVariants[1];
  const slug = product.title.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");

  return {
    name: slug,
    description: product.tagline,
    variant: variant.tier,
    folderStructure: generateFolderStructure(variant),
    readme: generateFullReadme(product, variant),
    dockerCompose: generateDockerCompose(variant),
    envExample: generateEnvExample(variant),
    packageJson: generatePackageJson(product, variant),
    mainConfig: generateMainConfig(variant),
    agentFiles: generateAgentFiles(variant.agents),
    apiRoutes: generateApiRoutes(variant),
  };
}

function generateFolderStructure(variant: BuildVariant): Record<string, any> {
  const structure: Record<string, any> = {
    "src/": {
      "app/": {
        "page.tsx": "Main dashboard page",
        "layout.tsx": "Root layout with providers",
        "globals.css": "Global styles",
        "api/": {
          "chat/route.ts": "Chat API endpoint",
          "query/route.ts": "Query processing",
          "agents/route.ts": "Agent management",
        },
      },
      "components/": {
        "ui/": "shadcn/ui components",
        "ChatPanel.tsx": "AI chat interface",
        "Dashboard.tsx": "Main dashboard",
        "KnowledgeGraph.tsx": "Interactive knowledge graph",
        "AgentStatus.tsx": "Agent pipeline status",
      },
      "lib/": {
        "agents/": variant.agents?.map(a => `${a.name.replace(/\s+/g, "")}.ts`) || [],
        "memory/": {
          "store.ts": "Memory store",
          "embedding.ts": "Embedding utilities",
        },
        "rag/": {
          "pipeline.ts": "RAG pipeline",
          "retriever.ts": "Document retriever",
        },
        "llm/": {
          "provider.ts": "LLM abstraction",
        },
      },
    },
    "prisma/": {
      "schema.prisma": "Database schema",
    },
    "public/": "Static assets",
    "docker-compose.yml": "Docker services",
    "Dockerfile": "Container build",
    ".env.example": "Environment variables",
    "README.md": "Project documentation",
    "package.json": "Dependencies",
  };

  return structure;
}

function generateFullReadme(product: ProductBuild, variant: BuildVariant): string {
  return `# ${product.title}

${product.tagline}

## Overview
${product.description}

## Target Audience
${product.targetAudience}

## Unique Value
${product.uniqueValue}

## Architecture
${variant.techStack?.map(t => `- **${t.layer}**: ${t.technologies.join(", ")}`).join("\n") || "See architecture diagram"}

## Agents
${variant.agents?.map(a => `- **${a.name}** (${a.role}): ${a.description}`).join("\n") || "See agent documentation"}

## System Flow
${variant.systemFlow?.map(s => `1. **${s.label}**: ${s.description}`).join("\n") || "See flow diagram"}

## Capabilities
${product.capabilities.map(c => `- **${c.label}**: ${c.description}`).join("\n")}

## Product Score
- Market Demand: ${product.productScore.marketDemand}/10
- Technical Feasibility: ${product.productScore.technicalFeasibility}/10
- Innovation: ${product.productScore.innovation}/10
- Ecosystem Maturity: ${product.productScore.ecosystemMaturity}/10
- **Final Score: ${product.productScore.finalScore}/10**

## Build Variant: ${variant.label}
- **Tier**: ${variant.tier}
- **Estimated Time**: ${variant.estimatedTime}
- **Difficulty**: ${variant.difficulty}

## Getting Started

\`\`\`bash
# Clone and install
git clone <your-repo>
cd ${product.title.toLowerCase().replace(/\s+/g, "-")}
npm install

# Set up environment variables
cp .env.example .env.local

# Run development server
npm run dev
\`\`\`

## Docker Setup

\`\`\`bash
# Start all services
docker-compose up -d

# View logs
docker-compose logs -f
\`\`\`

## Monetization Roadmap
${product.monetization.map(m => `- **Phase ${m.phase}** (${m.timeline}): ${m.label} — ${m.revenue}`).join("\n")}

---
Generated by **AI Product Builder Engine**
`;
}

function generateDockerCompose(variant: BuildVariant): string {
  const hasMemory = variant.techStack?.some(t => t.layer === "Memory");
  const hasDB = variant.techStack?.some(t => t.layer === "Backend" || t.layer === "Data");

  return `version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
     ${hasMemory ? `- chroma` : ''}

${hasMemory ? `  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ANONYMIZED_TELEMETRY=FALSE

` : ''}${hasDB ? `  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aidev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpassword
    volumes:
      - pg_data:/var/lib/postgresql/data

` : ''}volumes:
${hasMemory ? `  chroma_data:` : ''}${hasDB ? `\n  pg_data:` : ''}
`;
}

function generateEnvExample(variant: BuildVariant): string {
  return `# ============================================================
# ${variant.label} — Environment Configuration
# ============================================================

# LLM API Keys
OPENAI_API_KEY=your-openai-key
ANTHROPIC_API_KEY=your-anthropic-key

# Database
DATABASE_URL=file:./dev.db
# For PostgreSQL: postgresql://dev:devpassword@localhost:5432/aidev

# Vector DB (if using Chroma)
CHROMA_URL=http://localhost:8000

# Auth
NEXTAUTH_SECRET=your-secret-key-here
NEXTAUTH_URL=http://localhost:3000

# App
NEXT_PUBLIC_APP_URL=http://localhost:3000
NODE_ENV=development
`;
}

function generatePackageJson(product: ProductBuild, variant: BuildVariant): Record<string, any> {
  const slug = product.title.toLowerCase().replace(/\s+/g, "-");
  return {
    name: slug,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
      db: "prisma studio",
      "db:push": "prisma db push",
      "db:generate": "prisma generate",
    },
    dependencies: {
      next: "^16.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "@prisma/client": "latest",
      "z-ai-web-dev-sdk": "latest",
      tailwindcss: "^4.0.0",
      "framer-motion": "^11.0.0",
      "@xyflow/react": "^12.0.0",
      zod: "^3.23.0",
      sonner: "^1.7.0",
      yaml: "^2.4.0",
    },
    devDependencies: {
      typescript: "^5.6.0",
      prisma: "latest",
      "@types/node": "^22.0.0",
      "@types/react": "^19.0.0",
    },
  };
}

function generateMainConfig(variant: BuildVariant): string {
  return `// ============================================================
// AI System Configuration
// Generated by AI Product Builder Engine
// ============================================================

export const config = {
  // Agent Configuration
  agents: {
${variant.agents?.map(a => `    "${a.name.replace(/\s+/g, "").toLowerCase()}": {
      enabled: true,
      role: "${a.role}",
      description: "${a.description}",
    },`).join("\n") || ""}
  },

  // Tech Stack
  techStack: {
${variant.techStack?.map(t => `    "${t.layer.toLowerCase()}": [${t.technologies.map(t => `"${t}"`).join(", ")}],`).join("\n") || ""}
  },

  // Build Info
  build: {
    tier: "${variant.tier}",
    label: "${variant.label}",
    estimatedTime: "${variant.estimatedTime}",
    difficulty: "${variant.difficulty}",
  },

  // Memory Configuration
  memory: {
    provider: "chromadb",
    url: process.env.CHROMA_URL || "http://localhost:8000",
    embeddingModel: "text-embedding-3-small",
  },

  // LLM Configuration
  llm: {
    defaultProvider: "openai",
    models: {
      chat: "gpt-4o",
      embedding: "text-embedding-3-small",
    },
  },
};
`;
}

function generateAgentFiles(agents: AgentRole[]): Array<{ path: string; content: string }> {
  return agents.map(agent => {
    const className = agent.name.replace(/\s+/g, "");
    const slug = className.toLowerCase();

    return {
      path: `src/lib/agents/${slug}.ts`,
      content: `// ============================================================
// ${agent.name} Agent
// Role: ${agent.role}
// ${agent.description}
// ============================================================

export class ${className}Agent {
  private role = "${agent.role}";

  async execute(input: string, context?: Record<string, any>): Promise<string> {
    // TODO: Implement ${agent.name} logic
    console.log(\`[${this.role}] Processing: \${input}\`);
    return \`Processed by ${agent.name}: \${input}\`;
  }

  async processWithMemory(input: string, memory: any[]): Promise<string> {
    // TODO: Add memory-augmented processing
    return this.execute(input);
  }
}

export const ${slug}Agent = new ${className}Agent();
`,
    };
  });
}

function generateApiRoutes(variant: BuildVariant): Array<{ path: string; content: string }> {
  return [
    {
      path: "src/app/api/chat/route.ts",
      content: `import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  const { message } = await req.json();

  // TODO: Connect to your agent pipeline
  const response = \`Processing: \${message}\`;

  return NextResponse.json({ response });
}`,
    },
    {
      path: "src/app/api/agents/route.ts",
      content: `import { NextRequest, NextResponse } from "next/server";

export async function GET() {
  // Return agent status
  return NextResponse.json({
    agents: ${JSON.stringify(variant.agents?.map(a => ({ name: a.name, role: a.role, status: "idle" })) || [])},
  });
}`,
    },
  ];
}
