import type { RepoRole, RepoCatalogItem } from './types'

export const REGULATED_INDUSTRIES = new Set([
  'healthcare',
  'health-care',
  'finance',
  'financial-services',
  'insurance',
  'legal',
  'government',
  'public-sector',
  'pharma',
])

export const FIELD_ALIASES: Array<{ matches: string[]; tag: import('./types').FieldTag }> = [
  { matches: ['ai', 'artificial intelligence', 'llm', 'agents', 'agentic'], tag: 'ai' },
  { matches: ['automation', 'rpa', 'ops', 'operations'], tag: 'automation' },
  { matches: ['analytics', 'bi', 'dashboard', 'reporting'], tag: 'analytics' },
  { matches: ['devops', 'platform', 'sre', 'observability'], tag: 'devops' },
  { matches: ['security', 'compliance', 'identity', 'auth'], tag: 'security' },
  { matches: ['data', 'etl', 'warehouse', 'lakehouse'], tag: 'data' },
  { matches: ['rag', 'retrieval', 'knowledge', 'vector'], tag: 'rag' },
  { matches: ['workflow', 'orchestration', 'scheduler'], tag: 'workflow' },
  { matches: ['integration', 'api', 'connectors'], tag: 'integration' },
]

export const REPO_CATALOG: RepoCatalogItem[] = [
  {
    fullName: 'vercel/next.js',
    url: 'https://github.com/vercel/next.js',
    description: 'Production web framework for operator dashboards, portals, and API routes.',
    roles: ['interface'],
    tags: ['web', 'ui', 'dashboard', 'portal', 'api'],
    maturity: 95,
    activeSignal: 'Large production footprint across SaaS products.',
    selectionHint: 'Best fit when the product needs an authenticated operator workspace.',
  },
  {
    fullName: 'langchain-ai/langchain',
    url: 'https://github.com/langchain-ai/langchain',
    description: 'Agent runtime and tool abstraction layer for structured business workflows.',
    roles: ['agent'],
    tags: ['ai', 'agent', 'rag', 'workflow'],
    maturity: 90,
    activeSignal: 'Widely adopted for production LLM orchestration patterns.',
    selectionHint: 'Strong default for tool-using task agents and typed business flows.',
  },
  {
    fullName: 'microsoft/autogen',
    url: 'https://github.com/microsoft/autogen',
    description: 'Multi-agent framework for collaborative planning, review, and escalation.',
    roles: ['agent'],
    tags: ['ai', 'agent', 'multi-agent'],
    maturity: 87,
    activeSignal: 'Strong enterprise mindshare for agent collaboration.',
    selectionHint: 'Useful when the product needs specialist agents or reviewer loops.',
  },
  {
    fullName: 'langchain-ai/langgraph',
    url: 'https://github.com/langchain-ai/langgraph',
    description: 'Stateful orchestration engine for planner-led agent execution graphs.',
    roles: ['orchestration'],
    tags: ['ai', 'workflow', 'planner', 'stateful'],
    maturity: 89,
    activeSignal: 'Rapid adoption for durable agent state machines.',
    selectionHint: 'Maps cleanly to the planner layer required in the execution graph.',
  },
  {
    fullName: 'temporalio/temporal',
    url: 'https://github.com/temporalio/temporal',
    description: 'Durable workflow engine for retries, SLAs, and long-running business processes.',
    roles: ['workflow'],
    tags: ['workflow', 'durable', 'automation', 'orchestration'],
    maturity: 94,
    activeSignal: 'Proven at scale for mission-critical business workflows.',
    selectionHint: 'Best when the system needs resumable, auditable, long-running jobs.',
  },
  {
    fullName: 'n8n-io/n8n',
    url: 'https://github.com/n8n-io/n8n',
    description: 'Connector-rich workflow automation platform for business system integrations.',
    roles: ['workflow'],
    tags: ['workflow', 'automation', 'integration', 'connectors'],
    maturity: 91,
    activeSignal: 'Strong usage in integration-heavy internal tooling stacks.',
    selectionHint: 'Best when the system needs fast connector breadth and human-friendly automation.',
  },
  {
    fullName: 'microsoft/playwright',
    url: 'https://github.com/microsoft/playwright',
    description: 'Reliable browser and web automation runtime for operational task execution.',
    roles: ['execution'],
    tags: ['automation', 'browser', 'integration', 'testing'],
    maturity: 93,
    activeSignal: 'Actively maintained automation runtime with broad ecosystem support.',
    selectionHint: 'Ideal when execution must touch third-party portals or brittle web workflows.',
  },
  {
    fullName: 'celery/celery',
    url: 'https://github.com/celery/celery',
    description: 'Distributed task execution framework for backend jobs and asynchronous workloads.',
    roles: ['execution'],
    tags: ['execution', 'jobs', 'automation', 'backend'],
    maturity: 89,
    activeSignal: 'Long-lived background job runtime with strong operational familiarity.',
    selectionHint: 'Best for service-side execution that does not require browser automation.',
  },
  {
    fullName: 'supabase/supabase',
    url: 'https://github.com/supabase/supabase',
    description: 'Postgres-based application platform for transactional storage, auth, and APIs.',
    roles: ['storage'],
    tags: ['storage', 'database', 'auth', 'api'],
    maturity: 92,
    activeSignal: 'Popular application backend foundation with strong developer velocity.',
    selectionHint: 'Good default operational store for cases, users, and audit records.',
  },
  {
    fullName: 'qdrant/qdrant',
    url: 'https://github.com/qdrant/qdrant',
    description: 'Vector database for semantic retrieval over documents, events, and evidence.',
    roles: ['storage'],
    tags: ['storage', 'vector', 'rag', 'retrieval', 'ai'],
    maturity: 88,
    activeSignal: 'Actively used in production RAG systems and semantic search stacks.',
    selectionHint: 'Best when agent decisions need retrieval over unstructured evidence.',
  },
  {
    fullName: 'grafana/grafana',
    url: 'https://github.com/grafana/grafana',
    description: 'Observability and operational analytics UI for workflow health and business KPIs.',
    roles: ['monitoring', 'interface'],
    tags: ['monitoring', 'analytics', 'dashboard', 'observability'],
    maturity: 96,
    activeSignal: 'Battle-tested monitoring surface with strong alerting and dashboard support.',
    selectionHint: 'Best for operational visibility, SLA tracking, and run-level observability.',
  },
  {
    fullName: 'open-telemetry/opentelemetry-collector',
    url: 'https://github.com/open-telemetry/opentelemetry-collector',
    description: 'Telemetry pipeline for traces, metrics, and logs across product services.',
    roles: ['monitoring'],
    tags: ['monitoring', 'observability', 'telemetry', 'devops'],
    maturity: 91,
    activeSignal: 'Standard observability backbone across modern platform teams.',
    selectionHint: 'Best when the stack needs portable telemetry and vendor-neutral tracing.',
  },
  {
    fullName: 'keycloak/keycloak',
    url: 'https://github.com/keycloak/keycloak',
    description: 'Identity and access management platform for regulated or enterprise environments.',
    roles: ['security'],
    tags: ['security', 'identity', 'auth', 'compliance'],
    maturity: 91,
    activeSignal: 'Common enterprise identity layer for audited business systems.',
    selectionHint: 'Important when the product handles regulated workflows or privileged operations.',
  },
]

export const ROLE_ORDER: RepoRole[] = [
  'interface',
  'agent',
  'orchestration',
  'workflow',
  'execution',
  'storage',
  'monitoring',
]
